export const REQUESTED_THOUGHTS = 'REQUESTED_THOUGHTS';
export const RECEIVED_THOUGHTS = 'RECEIVED_THOUGHTS';

export const CREATE_THOUGHT = 'CREATE_THOUGHT';
export const SUCCESSFULLY_CREATED_THOUGHT = 'SUCCESSFULLY_CREATED_THOUGHT';
export const FAILED_TO_CREATE_THOUGHT = 'FAILED_TO_CREATE_THOUGHT';

export const CHANGE_CATEGORY = 'CHANGE_CATEGORY';
export const CHANGE_THOUGHT = 'CHANGE_THOUGHT';

export const FORGET_THOUGHT = 'FORGET_THOUGHT';
export const FORGOT_THOUGHT = 'FORGOT_THOUGHT';
