version: 2
jobs:
  build:
    working_directory: ~/thoughts
    docker:
      - image: circleci/node:latest-browsers
      - image: mysql:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - .node_modules
      - run: yarn test

test:
  override:
    - "JEST_JUNIT_OUTPUT=$CIRCLE_TEST_REPORTS/jest/junit.xml yarn test"